### ISSUE TITLE
Maven dependancy difference

### ISSUE THREAD

**Issue by joeynaor** [jfrog/jfrog-idea-plugin#106]
When scanning the exact same Maven project, different results/vulnerabilities are shown in the JFrog-supported IDEs. It appears that Eclipse has the most accurate data and number of dependancies, and that IntelliJ (and VSCode) provide different results, likely due to certain dependancies not showing up.

As the JFrog IntelliJ plugin is limited to what the IDE (IntelliJ) allows it to view/use, the purpose of this ticket is to investigate if anything can be done (on the plugin level) to improve this behavior and achieve uniformity across all JFrog-supported IDEs.

**Screenshot**
![comparison](https://user-images.githubusercontent.com/50103918/107140990-99856380-692e-11eb-8d7a-912fa6204f06.jpg)

**Versions**
- JFrog IDEA plugin version: 1.7.0
- Operating system: Windows Server 2019
- Xray version: 3.x

**Comment by yahavi** [comment]
@joeynaor,
To get the best performance for the dependency scanning, we extract the Maven dependencies from the IDE Maven plugins in Eclipse and IntelliJ. Using this method allows us to avoid redundant Maven dependency resolution.

For example, in IntelliJ, to see the dependencies resolved by the Maven plugin, open the Maven tab -> dependencies:
![image](https://user-images.githubusercontent.com/11367982/107146986-255db680-6954-11eb-9c8a-f4aa275df957.png)

There are more differences caused by the different attitudes of the Maven plugins in Intellij and Eclipse. 
One difference I've found is that the Eclipse plugin shows transitive [optional dependencies](https://maven.apache.org/guides/introduction/introduction-to-optional-and-excludes-dependencies.html#optional-dependencies) and the Intellij plugin does not. This is not an issue, since optional transitive dependency is ignored if not mentioned specifically as a direct dependency. For example see the [guice-plexus-shim](https://github.com/sonatype/sisu/blob/sisu-2.3.0/sisu-inject/containers/guice-plexus/sisu-inject-plexus/pom.xml#L48) under `maven-compat` -> `sisu-inject-plexus`.

Notwithstanding, I did find something [somtthing](https://github.com/jfrog/jfrog-idea-plugin/pull/107) we can change in the Intellij plugin whereby dependencies deduped if they are appearing twice in the same module.
