### ISSUE TITLE
Unable to authenticate when using SAML Integration

### ISSUE THREAD

**Issue by stephen-murby** [jfrog/jfrog-idea-plugin#2]
We are using Artifactory as a SAML authentication provider, as such are users do not have credentials for Xray. While this is ok for logging into the Xray front end, I can't find a way to have the plugin authenticate in this way?

**Comment by eyalbe4** [comment]
@stephen-murby,
Xray can be configured to use SAML through the Artifactory instance it is connected to.
You can read more about this [here](https://www.jfrog.com/confluence/display/XRAY/Authentication).
Please let us know if this helps.

**Comment by stephen-murby** [comment]
@eyalbe4 We have configured xray to use the SAML authentication, via Artifactory as the provider and this works perfectly to be able to login to the web front end (UI). 

However configuring the plugin to use the credentials artifactory requires (in my case case domain SSO credentials) and testing auth with xray gets me a HTTP 401. So my issue is specifically with seemingly not being able to use the intelliJ plugin while xray is configured to proxy authentication over to artifactory.

**Comment by eyalbe4** [comment]
Thank you @stephen-murby.
I'll check this and get back to you.

**Comment by eyalbe4** [comment]
@@stephen-murby.
The SAML authentication mechanism works only from the bowser, but there's something else that may work for you. Please try using the API Key from the Artifactory Profile page as described [here](https://www.jfrog.com/confluence/display/RTF/Updating+Your+Profile) as the Xray password in IDEA.
Since your developers should be able to access their profile page, this could be a good solution.
Please let us know if this works and we'll add this to the plugin documentation.

**Comment by stephen-murby** [comment]
@eyalbe4 The method you describe works perfectly, I haven't tried with an account that is not an administrator of Artifactory yet but I will ask someone to check for me 😄. 

Thanks for your help.
