### ISSUE TITLE
gradle scan is failing in 1.16.0

### ISSUE THREAD

**Issue by kakakpy** [jfrog/jfrog-idea-plugin#225]
**Describe the bug**
```
6:22 PM	Illegal base64 character 20
				[ERROR] Xray Scan failed: IllegalArgumentException: Illegal base64 character 20
				java.lang.IllegalArgumentException: Illegal base64 character 20
				at java.base/java.util.Base64$Decoder.decode0(Base64.java:746)
				at java.base/java.util.Base64$Decoder.decode(Base64.java:538)
				at java.base/java.util.Base64$Decoder.decode(Base64.java:561)
				at com.jfrog.ide.common.gradle.GradleTreeBuilder.createDependencyTrees(GradleTreeBuilder.java:67)
				at com.jfrog.ide.common.gradle.GradleTreeBuilder.buildTree(GradleTreeBuilder.java:52)
				at com.jfrog.ide.idea.scan.GradleScanManager.buildTree(GradleScanManager.java:90)
				at com.jfrog.ide.idea.scan.ScanManager.scanAndUpdate(ScanManager.java:130)
				at com.jfrog.ide.idea.scan.ScanManager$1.run(ScanManager.java:174)
				at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:962)
				at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:472)
				at com.intellij.open... (show balloon)

```

**Versions**
- JFrog IDEA plugin version:1.16.0
- Operating system: mac
- Xray version: 3.51.3

**Additional context**

**Comment by Millieel** [comment]
1. Gradle version: 6.5
2. Java Version: 1.8.0_231
3. no special characters
4. the output: 
gradle clean generateDepTrees -I init.gradle -q
Applying Gradle plugin from: file:/Users/username/.gradle/caches/jars-9/4ad572059a4588928290a59ded998f8e/bran-gradle-plugins-1.15.0-39-93be180c45.jar!/base.gradle

FAILURE: Build failed with an exception.

* Where:
Script 'jar:file:/Users/username/.gradle/caches/jars-9/4ad572059a4588928290a59ded998f8e/bran-gradle-plugins-1.15.0-39-93be180c45.jar!/base.gradle' line: 51

* What went wrong:
A problem occurred evaluating script.
> Could not find method compile() for arguments [{group=io.swagger.core.v3, name=swagger-annotations, version=2.0.10}] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 20s

**Comment by yahavi** [comment]
Thanks for this input, @Millieel!
The JFrog IDEA plugin builds the Gradle dependency tree using hooks in Gradle code. I'm afraid in your case the code does not compile and therefore the plugin failed to build the dependency tree.

The "compile" scope is no longer supported in Gradle 6. See - https://docs.gradle.org/current/userguide/upgrading_version_5.html. Could you please try to follow this guide to make your code compile on Gradle 6? For example, in your case, you can try to switch "compile" to "implementation".

Also - do you see the same error as @kakakpy sees? I couldn't reproduce the `Illegal base64 character` error yet.

**Comment by Millieel** [comment]
Yes, I reported the issue and the support team guided me to the link, I have the exact same issue.
JFrog IDEA plugin version:1.16.0
Operating system: mac
IDE: Intellij IDEA.
Additionally, My project builds successfully. The solution @yahavi  mentioned shows build failed. 

Can you @yahavi provide more detailed info about how to solve the problem? Not to mention, It's company scope using the Xray, It's not a good idea to change all project Gradle configurations in order to to use Xray IDE integration.

**Comment by yahavi** [comment]
Thanks for this information @Millieel.
We're sorry for this issue and we are still working to resolve it.

This error may happen when using Gradle 7 with "compile" dependencies configurations (see https://docs.gradle.org/current/userguide/upgrading_version_6.html#sec:configuration_removal). However, in Gradle 6 it shouldn't happen. Are you sure that your Gradle version is 6.5? If you have a Gradle wrapper installed, could you please try to run generateDepTrees with the wrapper instead of the global Gradle installation?
```
./gradlew clean generateDepTrees -I init.gradle -q
```

I didn't ask to change all Gradle configurations but only to investigate this specific project. The "Illegal base64 character" error happens when the output of `generateDepTrees` is unexpected. Once we managed to understand how to reproduce this output, we will be able to resolve this issue. 
Therefore, if possible, the most helpful information would be to provide a minimal reproducer.

**Comment by Millieel** [comment]
Thank you for your response. We are using the Gradle Wrapper.
Gradle distribution:  gradle-6.5
Gradle 7.4.2
`./gradlew clean generateDepTrees -I init.gradle -q` runs successfully, but the JFrog Xray Scan still doesn't work.

**Comment by yahavi** [comment]
Thanks for your response, @Millieel.
The JFrog IDEA plugin runs and parses the output of a custom Gradle plugin: [gradle-dep-tree](https://github.com/jfrog/gradle-dep-tree). My best guess is that one of your Gradle plugins writes to the stdout. The JFrog IDEA plugin reads the output and tries to parse it. As a result, we see these “Illegal base64 character” errors.

@Millieel & @kakakpy
We created a snapshot that changes this behavior a bit - instead of parsing the output, it writes the output to a file. I also added some extra logging.
Could you please check if that works for you? [JFrog-1.16.x-SNAPSHOT.zip](https://github.com/jfrog/jfrog-idea-plugin/files/9752005/JFrog-1.16.x-SNAPSHOT.zip)
Click [Here](https://www.jetbrains.com/help/idea/managing-plugins.html#install_plugin_from_disk) for instructions to install an IntelliJ IDEA plugin from disk.

Thanks in advance.

**Comment by yahavi** [comment]
@kakakpy @Millieel,
JFrog IDEA plugin 1.16.1 had been released.
This version includes the fix for this issue.
Feel free to upgrade - we'd appreciate your feedback on that.
