### ISSUE TITLE
plugin consistently segfaults IntelliJ when attempting to view dependency report

### ISSUE THREAD

**Issue by kevinross** [jfrog/jfrog-idea-plugin#380]
https://github.com/jfrog/jfrog-idea-plugin/blob/8d1d2408891ab73981808067b86eca301ba67bd2/src/main/java/com/jfrog/ide/idea/ui/webview/WebviewManager.java#L28

When I attempt to click through a gutter icon for a vulnerable dependency, the plugins causes the entire IDE to crash. Every time.

Crash Report (with some sections removed for space and relevance, I can include them but I'm pretty sure they're entirely irrelevant):

https://gist.github.com/kevinross/87c2ac0090ca9b9c8db385c91490257c

**Comment by asafgabai** [comment]
Hi @kevinross, thanks for reporting this issue. It seems to happen on IntelliJ 2023.2, following some changes in JCEF that were added in this release. We use JCEF in our plugin to show the issue details panel (the right panel).
A fix for this issue is released in version 2.3.1 of the plugin.
We'd appreciate your feedback on it.
